### ISSUE TITLE
moeclub提供的mail.ac.id临时邮箱无法注册应用

### ISSUE THREAD

**Issue by Stanla** [donwa/oneindex#103]
![image](https://user-images.githubusercontent.com/15817126/40822367-6a925308-659e-11e8-8451-ccba4a24b8bf.png)

**Comment by Stanla** [comment]
用之前的版本在验证时会出现问题，“ju.tn”无法访问

**Comment by donwa** [comment]
可能是域名没有管理员吧。 新版你可以用个人账号，只是空间小了点。

**Comment by Stanla** [comment]
那请问旧版还能用嘛？(2.0)
