### ISSUE TITLE
安装失败怎么解？？？

### ISSUE THREAD

**Issue by kakkk** [donwa/oneindex#107]
创建好了之后登陆，第一次显示了发布者和权限那个界面，然后回到oneindex显示绑定失败，然后就绑定账户的时候登陆完就跳回去显示安装失败了
![qq 20180601194215](https://user-images.githubusercontent.com/23286793/40839271-5e2c19ce-65d4-11e8-93a9-cd7a99c0945c.png)
换了个号都是这样，我是E3开发者版的全局

**Comment by donwa** [comment]
按照安装指引，重新申请secret安装

**Comment by kakkk** [comment]
谢谢，搞定了👍👍

**Comment by xman55555** [comment]
大佬为甚我重新申请还是不行?

**Comment by ddkk3000** [comment]
知道怎么解决了，直接重新申请就行了
