### ISSUE TITLE
找到显示HEAD.md原办法了

### ISSUE THREAD

**Issue by platoer** [donwa/oneindex#108]
这个文件里IndexController.php，修正后正常显示了：
![code](https://i.loli.net/2018/06/01/5b115329282fa.png)

不过README.md又不显示了:)

**Comment by donwa** [comment]
谢谢，我明白问题的原因了。

不过不是你那样修复。

另外新增了index.html 的特性。如果文件夹下存在index.html 直接输出index.html

**Comment by platoer** [comment]
嗯，只要找到原因就ok:) 我不懂，都是随便搜索代码的：）
