### ISSUE TITLE
3.0测试版目录名含空格刷新缓存时的新问题

### ISSUE THREAD

**Issue by heroxin** [donwa/oneindex#109]
之前递交的目录名含空格刷新会卡住的问题已初步得到解决，感谢开发者的辛勤努力。
不过在3.0测试版中又发现了新的问题，如果目录名含空格，现在刷新缓存时已经不会卡在这个目录无法继续了，但是会在索引完该目录后直接去索引同级目录，而无法递归索引该目录的子目录，也就是说无法为含空格目录的子目录刷新缓存。
同样的把空格改为下划线，则可以正常递归搜索子目录刷新所有子目录的缓存。

**Comment by donwa** [comment]
改了下代码，不知道修复没有。问题比较奇怪

**Comment by heroxin** [comment]
测试已能正常刷新含空格目录的子目录了，命令行输出的路径数量和cache目录里文件数量一致，应该是修复成功了:)

**Comment by heroxin** [comment]
好像不太对劲，刚才又试了下，命令行刷新缓存居然貌似失效了，手动刷新一遍后页面访问各个目录的响应时间和没有缓存时差不多。查看了一下cache目录，发现页面访问某个目录时会生成一个新的缓存文件，而不是用之前手动刷新生成的缓存文件，再次访问时响应速度立刻提高，应该是调用了第一次访问页面时生成的那个缓存文件，命令行手动刷新的缓存文件貌似没有起作用。

**Comment by heroxin** [comment]
@donwa cli刷新和管理后台刷新都是这样

**Comment by donwa** [comment]
再次修复。。。

**Comment by heroxin** [comment]
谢谢，测试缓存功能已全部正常
