### ISSUE TITLE
去掉链接中的 /?/ 没看懂...

### ISSUE THREAD

**Issue by wxlost** [donwa/oneindex#11]
去掉链接中的 /?/ :
需要添加apache/nginx/iis的rewrite的配置文件
参考程序根目录下的：.htaccess或nginx.conf或Web.config  

    'root_path' => '?' 
改为

    'root_path' => '?' 

这2个'root_path' => '?' 不是一样吗.....

**Comment by donwa** [comment]
已修改。。。
