### ISSUE TITLE
关于功能

### ISSUE THREAD

**Issue by WangNingkai** [donwa/oneindex#123]
我感觉不需要添加很多功能，简单实用就好，version2就比较简单。
说一下存在的问题
1.图床创建的目录在onedrive的根目录下，如果使用者的目录为/share，就无法查看。
2.路径问题，后台采用的路由模式，默认多了/?/，不过是用使用rewrite可以去除，但是不完全，登陆的话/login，会跳转到/login/admin出错。
3.关于上传功能，现在用起来多少有点问题。
4.总体来说，这个版本改动多，但还有点问题，不过感谢作者的贡献，有这么好的开源作品

**Comment by donwa** [comment]
1、已修复
2、已修复，后台不应该去掉/?/。
3、web端实要现后台上传大文件，本来就是用的一些奇淫技巧，与运行环境上传文件大小有很大关系。
