### ISSUE TITLE
404

### ISSUE THREAD

**Issue by hatvgit** [donwa/oneindex#13]
<?php return array (
  'client_id' => 'ea2b36f6-b8ad-40be-bc0f-e5e4a4a7d4fa',
  'client_secret' => 'EIVCx5ztMSxMsga18MQ7rmGf9EIP7zv6tfimb0Kp5Uc=',
  'redirect_uri' => 'https://ju.tn/onedrive-login',
  'onedrive_root'=> '/Documents/share', //onedrive中要共享的目录，默认为根目录，可以改成如: /share
  'cache_type'=> 'file',//sqlite 需要pdo 支持
  'cache_expire_time' => 3600,
  'cache_refresh_time' => 600,
  'root_path' => '?'
);
 404

**Comment by donwa** [comment]
不明白你的意思。这个是配置文件，不用访问。

**Comment by gaojianye** [comment]
是不是打开文件404错误？是nginx conf配置有错误应该
