### ISSUE TITLE
希望增加漫画阅览模式 即多图浏览模式

### ISSUE THREAD

**Issue by anqi911** [donwa/oneindex#134]
https://drive.lofter.cc/ImageTest_View/
像这个一样  直接列目录下图片

**Comment by XiaoPika** [comment]
这个好！

**Comment by xzc0001** [comment]
这个页面其实就是用img标签，自己改一下就可以了。可能需要加个判断。至于判断方法感觉可以参考一下readme.md 和header.md

**Comment by anqi911** [comment]
求教...我php新手 @xzc0001
