### ISSUE TITLE
绑定账号的时候报错 AADSTS90014

### ISSUE THREAD

**Issue by zhengjian93** [donwa/oneindex#140]
登录
抱歉，登录时遇到问题。

AADSTS90014: The request body must contain the following parameter: 'client_id'.

**Comment by XiaoPika** [comment]
我之前安装的时候也出现这个问题，原因是你 client_id 没有写在下一步跳转的 URL 里，还有 return_url 及code 也没有，所以不止这一个问题。检查 nginx 的 rewrite 功能是否开启与 cache 及 config 文件夹的读写权限是否授予（使用 FTP 管理软件如 FlashFXP 授予读写权限并不完整，具体原因不详，仍需在控制台使用 sudo chmod 命令），我重新给予两个文件夹 666 权限后可正常跳转。

（遇到问题自己多思考解决之道，这个项目是非常棒的，作为一名用户我理想中的项目里的 issue 应更像是一种思考分享而不是询问客服）

**Comment by louis9527** [comment]
@zhengjian93 请问你的这个问题怎么解决的？
