### ISSUE TITLE
nginx下设置二级域名的伪静态问题

### ISSUE THREAD

**Issue by snoooowy** [donwa/oneindex#141]
使用的是wordpress的二级目录规则
server
    {
        listen 80;
        #listen [::]:80;
        server_name xxxxxxx.com ;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/xxxxxxxx;

        include rewrite/wp2.conf;
        #error_page   404   /404.html;
wp2.conf中设置如下
location /home/wwwroot/xxxxxx/ {
	try_files $uri $uri/ /home/wwwroot/xxxxxxx/index.php?$args;
}

# Add trailing slash to */wp-admin requests.
rewrite /wp-admin$ $scheme://$host$uri/ permanent;
现在问题是设置去掉?就404，是哪里配置出错了吗

**Comment by NoahNye** [comment]
网站目录下修改config/base.php文件里 'root_path' => '?', 为 'root_path' => '',

**Comment by snoooowy** [comment]
“网站目录下修改config/base.php文件里 'root_path' => '?', 为 'root_path' => '',”
这一步的作用不就是在后台页面打开  “去掉/?/ (需配合伪静态使用!!)”的开关么？已经这么做了还是会404

**Comment by NoahNye** [comment]
我重新建了个站发现单纯改base.php是会出现404的，您还需要配置下伪静态，以下是我根据其他网友配置：
if (!-f $request_filename){
set $rule_0 1$rule_0;
}
if (!-d $request_filename){
set $rule_0 2$rule_0;
}
if ($rule_0 = "21"){
rewrite ^/(.*)$ /index.php?/$1 last;
}

**Comment by snoooowy** [comment]
谢谢，问题解决。伪静态规则写错了。
