### ISSUE TITLE
使用盒子接电视播放视频时无法使用遥控点击播放

### ISSUE THREAD

**Issue by berrythinking** [donwa/oneindex#150]
在安卓盒子上使用浏览器打开网址，进入视频文件后使用遥控上下无法进入视频框内的播放，暂停，全屏按钮，直接点击视频框则是下载视频文件。只有在出现鼠标指针时可以定位到视频中部或左下的播放按钮。
请问修改哪个文件可以增加一列控制按钮使得遥控器也可以使用？或者直接点击视频框则播放视频且自动全屏？

**Comment by findwisdom** [comment]
这个我觉得你需要换个浏览器 或者查阅Dplayer文档
