### ISSUE TITLE
设置第二个密码不可用

### ISSUE THREAD

**Issue by zzzop** [donwa/oneindex#163]
请问我在两个文件夹设置不同的密码，当第一个输入密码进入后，进入另一个文件夹输入密码确认后，页面刷新没有进入文件夹怎么解决呢，我该排查哪部分的问题

**Comment by OctLan** [comment]
这是个bug  缓存的密码都为第一次访问.password 
修复如下
https://github.com/donwa/oneindex/pull/165/files

**Comment by zzzop** [comment]
@OctLan 原来如此，非常感谢
