### ISSUE TITLE
多目录有不同密码时有冲突

### ISSUE THREAD

**Issue by XGZepto** [donwa/oneindex#167]
我在两个不同的目录放置了两个内容不同的.password文件
结果两个目录的密码都变成了新的.password文件
应该不是浏览器缓存的锅吧

**Comment by XGZepto** [comment]
[原来之前已经修复过了](https://github.com/donwa/oneindex/commit/011847b237a3235f744fd2ae31a2b027d62d337fl)

**Comment by Zxilly** [comment]
只是有人交了pull request
### 然而作者并没有merge

**Comment by XGZepto** [comment]
我早按 pull request 的改好了

Zxilly <notifications@github.com> 于2018年7月22日周日 下午3:41写道：
