### ISSUE TITLE
设置伪静态后，图床上传图片完成自动跳转404

### ISSUE THREAD

**Issue by XGZepto** [donwa/oneindex#168]
上传图片后的正确预览域名
https://yourdomain.com/images/20xx/xx/xx/xxx.jpg?s
但是自动跳转导致404的域名是
https://yourdomain.com//images/20xx/xx/xx/xxx.jpg?s
在images之前多了一个/
求问解决方案

**Comment by XGZepto** [comment]
`$url = $http_type.$_SERVER['HTTP_HOST'].$root.'/'.$remotefile.((config('root_path') == `'?')?'&s':'?s');`
把$root后面的/去掉就好了。。

**Comment by Zxilly** [comment]
@XGZepto 你可以交一个PR

**Comment by XGZepto** [comment]
反正他又不 merge
要交你交呗。

**Comment by donwa** [comment]
@XGZepto 代码不正确我也合并咯。
你这个代码会影响未做伪静态的环境。

功能已修复。

**Comment by woaijorden** [comment]
> `$url = $http_type.$_SERVER['HTTP_HOST'].$root.'/'.$remotefile.((config('root_path') == '?')?'&s':'?s');`
> 把$root后面的/去掉就好了。。

在哪个文件里？
