### ISSUE TITLE
用这个去列涉及版权的会导致VPS被ban掉么？

### ISSUE THREAD

**Issue by xzc0001** [donwa/oneindex#18]
之前在hostmybytes上的一个vps搞了一个，本地传了一点电子书到onedrive上，没几天vps就offline了，不过hostmybytes也没有说是不是因为版权或者违反ToS，联系工单只是给恢复了运行也没有给offline的原因。现在有点不敢再开了。

**Comment by donwa** [comment]
这和oneindex无关，不在讨论范围内。

另外，请尊重版权和相关法律法规。

**Comment by xzc0001** [comment]
谢谢。

**Comment by OHLIA** [comment]
@xzc0001 你这很可能是vps供应商服务器的问题。
