### ISSUE TITLE
UTF-8编码和Windows-1252编码转换问题

### ISSUE THREAD

**Issue by Zxilly** [donwa/oneindex#193]
![](https://i.loli.net/2018/07/20/5b51b02e6a424.png)
把UTF-8格式的字符读成了Windows-1252,应该怎么修？
服务器是Windows Server 2008 R2 上的Apache

**Comment by Zxilly** [comment]
成功定位bug
`Url中有Unicode编码包含有“\x85”的汉字字节（即encode后包含“%85”的汉字， 如：“关”、 “兲“、 “共“、 “兰“、 “儰”、 “䅰”、 “腰” 等），并且不是作为查询参数时，无法正常使用。`
娘耶，这怎么修？

**Comment by Zxilly** [comment]
现在目测是Apache的mod_rewrite的bug，怎么处理啊。。。

**Comment by Zxilly** [comment]
看起来应该还是Windows独占的。。。

**Comment by Zxilly** [comment]
@donwa 有救吗。。。。

**Comment by donwa** [comment]
感觉解决这个问题会带出很多新问题，想办法在apache上解决吧。

**Comment by Zxilly** [comment]
@donwa 您的服务器是跑在linux上的吗？我追踪了一下，发现数据在被发送给php之前就被apache返回了404

**Comment by donwa** [comment]
应该是判断uri不在重写规则中，然后就返回404了，没被重定位到index.php

**Comment by Zxilly** [comment]
Apache的bug，暂时无解，弃疗
