### ISSUE TITLE
縮略圖 自訂參數功能失效

### ISSUE THREAD

**Issue by Gdist** [donwa/oneindex#195]
[http://xn.tn/bg.jpg?t=100|100](http://xn.tn/bg.jpg?t=100|100)
回傳的網址最後會出現兩次參數，導致略縮圖都是800*800
&width=800&height=800&width=100&height=100
但更改第一組參數後就能調整成自訂的大小。

請問有辦法調整第一組參數嗎?
試著修改IndexController.php的參數，但仍然只會更改到第二組

**Comment by donwa** [comment]
修复
