### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by mlgexyz** [donwa/oneindex#208]
能不能在onedrive里存储每个文件的有关信息，比如下载次数（即解析次数）每次解析都+1、+1....

**Comment by mlgexyz** [comment]
顺带在oneindex里反映出来（可设置是否显示），每次重建缓存的时候就更新一下显示的数值

**Comment by urusai-me** [comment]
我觉得这个东西不是很现实，因为 **网盘文件和目录的名称是会变的** 。再者oneindex是脱离数据库的，那只能把下载次数信息都放到缓存文件里（或者专门为这个功能连接一个数据库？这样还得考虑文件名更改后数据清理的问题）。再者，当网盘文件很多时，查询和加载会对服务器端造成很大压力。（当然，列出这个可以通过前端方式实现）

**Comment by mlgexyz** [comment]
@XiaoPika 不蒜子应该不行，直链解析的时候不能加载js，我这边大部分来源都是直链解析过来的

**Comment by XiaoPika** [comment]
这样应该是个性化定制了吧，你的需求不适合大多数人
