### ISSUE TITLE
用js实现下载当前文件夹全部文件

### ISSUE THREAD

**Issue by urusai-me** [donwa/oneindex#209]
用document.getElemantsByClassName()之类的方法遍历文件链接，然后利用a标签的download属性来添加下载。
先留个条子备忘，有空再写～

**Comment by XiaoPika** [comment]
大佬提个PR啊~ 等不及donwa merge了我先自个儿找大佬实现这个功能了/笑哭

**Comment by urusai-me** [comment]
外地出差，没带电脑写不了

**Comment by XiaoPika** [comment]
wait you

**Comment by urusai-me** [comment]
`<div id="downall"><a id="downall" href="javascript:void(0);" onclick="downall()">下载全部</a></div>`

**Comment by XiaoPika** [comment]
感谢大佬~ 话说你给的demo站突然开始嚎叫的hentai 八嘎吓我一大跳！

**Comment by urusai-me** [comment]
回楼上，插入 `<script async src="https://kizuna.link/js/urusai.js"></script>` 即可获得钉宫病福利

**Comment by Rhilip** [comment]
因为get请求是下载，post请求是打开。
所以只要导出成txt或者类似的文本，剩下长时间的3xx跳转等待到正确下载地址以及下载交给专业下载器就行。

**Comment by XiaoPika** [comment]
确实，这种方法在文件夹里文件比较多的情况下会急死个人/笑哭，一秒钟弹一个窗口不关掉主页面有些时候弹几百个都有可能

**Comment by XiaoPika** [comment]
Rhilip 提供的办法比较好，应该用 PHP 或者 JS 可以很方便的打包所有链接生成一个 txt 或者其他类型的下载链接，这个需求就留待有需要的大佬们去完成吧/笑哭

**Comment by Rhilip** [comment]
@XiaoPika 基于JS实现，在上面大佬 @urusai-me 的基础上修改了点东西。这样就不用给item加`class="fileLinks"`的属性了，直接用下面替换原downall方法就行。

``` javascript
function downall() {
    let dl_link_list = Array.from(document.querySelectorAll("li a"))
        .map(x => x.href) // 所有list中的链接
        .filter(x => x.slice(-1) != "/"); // 筛选出非文件夹的文件下载链接
    let dl_link_str = dl_link_list.join("\r\n"); // 数组转str

    let blob = new Blob([dl_link_str], {
        type: 'text/plain'
    }); // 构造Blog对象
    let a = document.createElement('a'); // 伪造一个a对象
    a.href = window.URL.createObjectURL(blob); // 构造href属性为Blob对象生成的链接
    a.download = "file.txt"; // 文件名称，你可以根据你的需要，比如构造
    a.click() // 模拟点击
    a.remove();

}
```
仍然是使用`downall();` 调用

**Comment by XiaoPika** [comment]
大佬就是大佬（疯狂暗示）
用上啦！话说可以提个PR吧

**Comment by urusai-me** [comment]
膜大佬！
