### ISSUE TITLE
你好，文件上传好了之后打开网页是下载一个文件，内容是index.php里面的的内容

### ISSUE THREAD

**Issue by LoogCP** [donwa/oneindex#220]
你好，文件上传好了之后打开网页是下载一个文件，内容是index.php里面的的内容，
请问大神该怎么解决

**Comment by urusai-me** [comment]
你的主机不支持php吗？

**Comment by LoogCP** [comment]
安装了的

 apt list --installed |grep php                                                                                          Thu 16 Aug 2018 09:02:10 AM EDT

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libapache2-mod-php7.0/stable,stable,now 7.0.30-0+deb9u1 amd64 [installed,automatic]
php/stable,now 1:7.0+49 all [installed]
php-common/stable,now 1:49 all [installed,automatic]
php7.0/stable,stable,now 7.0.30-0+deb9u1 all [installed,automatic]
php7.0-cli/stable,stable,now 7.0.30-0+deb9u1 amd64 [installed,automatic]
php7.0-common/stable,stable,now 7.0.30-0+deb9u1 amd64 [installed,automatic]
php7.0-json/stable,stable,now 7.0.30-0+deb9u1 amd64 [installed,automatic]
php7.0-opcache/stable,stable,now 7.0.30-0+deb9u1 amd64 [installed,automatic]
php7.0-readline/stable,stable,now 7.0.30-0+deb9u1 amd64 [installed,automatic]

最开始是用宝塔的一键安装，不行， apt list --installed |grep php  没有输出，用apt安装之后输出如上，重启nginx也还是不行，直接下载index.php

**Comment by Zxilly** [comment]
你这是php没配置好，和项目一点关系没有。。。

**Comment by Zxilly** [comment]
nginx的conf改了吗

**Comment by LoogCP** [comment]
我看教程就是直接解压就能用，。。。我以为我的也可以，我不会写NGINX和php的配置，，，，尴尬了

**Comment by XiaoPika** [comment]
我比较好奇连 PHP 基础都不太明白的人是怎么知道这种小众 PHP 程序的/捂脸笑

**Comment by LoogCP** [comment]
@XiaoPika ...不小心在B站上面看到的，话说NGINX和php的配置很简单吗，最近科室的事情很多，没研究过

**Comment by XiaoPika** [comment]
@LoogCP emmm科室……你也是学医的吗←_← nginx配置你不需要搞懂，你要照着网上的傻瓜教程操作就行了，主要是php-fpm的安装与配置，你直接谷歌“直接弹出php下载”这种类似的关键词就可以找到大量的教程（非科班的自学就要多靠搜索）

**Comment by LoogCP** [comment]
@XiaoPika 嗦嘎，有时间看看，
是学医的，不过不是临床，检验。就是玩病人的血尿屎痰那种

**Comment by LoogCP** [comment]
@XiaoPika 哇，没想到还能遇到同行，幸会幸会

**Comment by XiaoPika** [comment]
@LoogCP 麻烦你点一下页尾的 close issue ^_^
