### ISSUE TITLE
绑定权限问题

### ISSUE THREAD

**Issue by forestzhang945** [donwa/oneindex#223]
![image](https://user-images.githubusercontent.com/9585063/44253042-d2965e80-a230-11e8-9476-efa2b2c036dd.png)
有没有朋友出现这个问题，管理员应该怎么设置这个权限问题呢？

**Comment by urusai-me** [comment]
如果使用教育版，请使用具有管理员权限的账号

**Comment by forestzhang945** [comment]
![image](https://user-images.githubusercontent.com/9585063/44262325-37f84880-a24d-11e8-9910-379abe3e6879.png)
搞定了，教育版admin用户后台设置权限即可

**Comment by forestzhang945** [comment]
- [ ]
