### ISSUE TITLE
手机端下载oneindex里面的apk后缀的文件，会触发oneindex几十秒内无法访问

### ISSUE THREAD

**Issue by maotongxue** [donwa/oneindex#229]
手机测试使用安卓和苹果都会触发，但是电脑浏览器下载apk后缀没问题，cache和config权限都给了，你们可以测试下，用的master分支

**Comment by maotongxue** [comment]
zip后缀不论多大，手机端都能下载，apk后缀一个3.4M的也能下载，但是15M和34M的两个文件都会触发oneindex无法访问，很奇怪

**Comment by XiaoPika** [comment]
看看服务端的日志有没有报错

**Comment by urusai-me** [comment]
无法复现错误。

**Comment by urusai-me** [comment]
https://seek.moe/Android应用/
