### ISSUE TITLE
怎么清除上传队列，这个bug太恼人了！！

### ISSUE THREAD

**Issue by AlbertETA** [donwa/oneindex#236]
为了提交这个ISSUE专门翻出许久不用的github号。
1.老哥设计下当按下“上传管理”页面“服务器文件/文件夹
远程目录”右面的“上传按钮”后会弹出**提示，确认后再上传文件**。
2.现在这个手稍微一滑，直接把我服务器目录文件就添加到上传队列，关键是还**没法删除终止正在上传的队列文件**，
3.一个一个手动点上传吧还是有bug，，刚把它**上传完**，下面他**又蹦出来**，无限停留在上传队列中，无法删除！！！！

**Comment by liankainan** [comment]
删除config文件夹下的upload.php和uploaded.php文件

**Comment by AlbertETA** [comment]
嗯，确实是这两个文件在记录数据

**Comment by AlbertETA** [comment]
希望作者大佬还是加上个上传确认提示
