### ISSUE TITLE
求一个站内搜索功能！

### ISSUE THREAD

**Issue by 91en** [donwa/oneindex#239]
求一个站内搜索功能！

**Comment by liankainan** [comment]
我习惯用ctrl+f

**Comment by 91en** [comment]
东西多了以后，你还是需要点开文件夹才能用ctrl+f。如果埋得深或者东西很多！几个T的，ctrl+f就没用了

**Comment by liankainan** [comment]
嗯，层级太多ctrl+f确实不适合用，只适合文件量不多的

**Comment by XiaoPika** [comment]
很早之前这个需求就人提了，看样子想让donwa大神添加几个刚需功能也难上加难，建议有能力自己动手丰衣足食，最好能在解决后提个 PR 造福大家，谢谢~

**Comment by 91en** [comment]
讲真，这个站内搜索，我没思路！搜索数据库的什么呢！？

**Comment by Zxilly** [comment]
@91en 缓存的设计是不分层级的。。。如果要搜索功能需要大改，上数据库，重构吧

**Comment by 91en** [comment]
那就有点太麻烦了！
