### ISSUE TITLE
这个代码是怎么触发的？ 

### ISSUE THREAD

**Issue by sichougudao** [donwa/oneindex#242]
function downall() {
    let dl_link_list = Array.from(document.querySelectorAll("li a"))
        .map(x => x.href) // 所有list中的链接
        .filter(x => x.slice(-1) != "/"); // 筛选出非文件夹的文件下载链接

    let blob = new Blob([dl_link_list.join("\r\n")], {
        type: 'text/plain'
    }); // 构造Blog对象
    let a = document.createElement('a'); // 伪造一个a对象
    a.href = window.URL.createObjectURL(blob); // 构造href属性为Blob对象生成的链接
    a.download = "folder_download_link.txt"; // 文件名称，你可以根据你的需要构造
    a.click() // 模拟点击
    a.remove();

在网站首页的右下角有个下载图标 怎么去除？
删除这段代码吗

**Comment by sichougudao** [comment]
让我去看什么

**Comment by Zxilly** [comment]
@sichoududao 去看commit记录，把我的commit回滚就行了，或者照着commit记录删掉对应的代码。
其实很好用的QaQ

**Comment by sichougudao** [comment]
已经解决

**Comment by sichougudao** [comment]
好的  我去关了

2018-09-07 21:20 GMT+08:00 Zxilly <notifications@github.com>:
