### ISSUE TITLE
非https,调用ju.tn中转

### ISSUE THREAD

**Issue by wxlost** [donwa/oneindex#246]
之前用着正常跟随git pull后一片空白 缓存啥的都试过不行.于是重新git并安装
我的域名是启用https的.可依然提示要中转.但是登陆账号那里提示域名不一致无法绑定.
最后我修改了`安装里的域名判断`为自己的就绑定成功了.
所以这里是bug吗还是我的机密key特殊?
看了一下安装判断这里对https的判断几乎没有啊.....
一脸懵逼

```
		if($_SERVER['HTTP_HOST'] == 'localhost'){
			$redirect_uri = 'http://'.$_SERVER['HTTP_HOST'].get_absolute_path(dirname($_SERVER['PHP_SELF']));
		}else{
			// 非https,调用ju.tn中转
			$redirect_uri = 'https://ju.tn/';
		}
```

**Comment by wxlost** [comment]
......原来如此.不过大佬忘记在安装界面那开放自己输入域名了.那个输入款禁止写入了.小白来安装就GG了

**Comment by simplove** [comment]
找到AdminController.php
删除里面的这段代码，成功显示出来。
我还以为是啥问题了，重装了N遍。。。
if($_SERVER['HTTP_HOST'] == 'localhost'){
			$redirect_uri = 'http://'.$_SERVER['HTTP_HOST'].get_absolute_path(dirname($_SERVER['PHP_SELF']));
		}else{
			// 非https,调用ju.tn中转
			$redirect_uri = 'https://ju.tn/';
		}

**Comment by wxlost** [comment]
@simplove 哈哈.是的.我之前就是卡在这里...掉巨坑里了.
