### ISSUE TITLE
nexmoe主题背景SVG怎么挂了。。

### ISSUE THREAD

**Issue by WA-YI** [donwa/oneindex#247]
访问主题预设的背景图“https://one.chainwon.com/博客图床/bg-bottom.svg”是404。
还有我上一个OneDrive账号被设为只读了（一直提示正在维护）。。怕不是管理员还是巨硬那边给。。

**Comment by donwa** [comment]
我把那个风格的css文件给更新了。
风格作者提交的时候，静态文件依赖他的个人网站的。
我把它转本地了。
