### ISSUE TITLE
今天发现文件列表没有任何文件显示

### ISSUE THREAD

**Issue by ernuan** [donwa/oneindex#248]
今天上传完文件之后 习惯性的打开看一下 却发现文件列表没有了任何文件 更新token缓存都无效

**Comment by ernuan** [comment]
![image](https://user-images.githubusercontent.com/36343710/45208107-62717a80-b2bc-11e8-927f-419aa4973c5b.png)
账号授权解除重新安装提示这个

**Comment by ernuan** [comment]
@donwa

**Comment by ernuan** [comment]
已解决

**Comment by fuhmin** [comment]
我也遇到这个问题，请教如何解决的

**Comment by ernuan** [comment]
> 我也遇到这个问题，请教如何解决的

记不太清了 去年的事情 如果重装一次之后没有效果 就尝试更改域名吧 这个域名指的是访问网盘的这个域名 我中间是更换了一次域名才恢复的
