### ISSUE TITLE
看到更新了手贱升级了一下结果，程序安装失败

### ISSUE THREAD

**Issue by SelfEnough** [donwa/oneindex#263]
下一步，复制粘贴client码，下一步，进行到账号绑定。就程序安装失败，手机电脑换了三个浏览器 都不行。。。
同样的主机环境，之前好好的

**Comment by q673428536** [comment]
mark，我的也不好好使，日志在哪里可以看到？

**Comment by AlbertETA** [comment]
建议重试，我之前也是到登录账户后安装失败，重试几次忽然又好了

**Comment by SelfEnough** [comment]
> 建议重试，我之前也是到登录账户后安装失败，重试几次忽然又好了

没用的 重试了不下20遍
