### ISSUE TITLE
自己设置的密码进不去

### ISSUE THREAD

**Issue by yxisboy** [donwa/oneindex#264]
大佬，按照教程建立了.password文件放在了文件夹里，可以显示出输入密码界面，但是输入自己的密码进不去是怎么回事啊？

**Comment by yxisboy** [comment]
已经处理好了，打扰了

**Comment by JERE-MIAH** [comment]
你好，问下你是怎么解决的呢？我也遇到了一样的问题

**Comment by yxisboy** [comment]
> 你好，问下你是怎么解决的呢？我也遇到了一样的问题
设置密码的时候，别加括号，直接写密码

**Comment by FancyKings** [comment]
我没有加括号，并且是在Linux命令下生成的文件，但是我输入自己设置的密码，还是进不去，这个请问遇到过吗，我清楚缓存也试过了，隔夜也试过了，真的不知道是哪里的问题

**Comment by aijoo2012** [comment]
你好，.password文件怎么弄。格式什么样的
