### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by AlliotTech** [donwa/oneindex#276]
![image](https://user-images.githubusercontent.com/24980252/46512916-d33e8f00-c888-11e8-9ba9-8992dbffb0a7.png)
由于服务器80端口被占用 所以端口设置的8080.
安装时样式貌似没能加载  
![image](https://user-images.githubusercontent.com/24980252/46512957-f1a48a80-c888-11e8-996d-007a680d1762.png)
docker run -d -p 8080:80 --name oneindex --restart=always yinaoxiong/oneindex

**Comment by lj98lj98** [comment]
同样，试过上百次，没有偶遇一次成功。
