### ISSUE TITLE
播放大文件视频是否存在卡顿？

### ISSUE THREAD

**Issue by louis9527** [donwa/oneindex#280]
5G多的视频文件，播放会有明显卡顿，如果将视频下载连接加入视频播放器中播放时又表现的很流畅。

网页对大文件播放不够良好吗？还是什么原因...

**Comment by SCGabriel** [comment]
> 5G多的视频文件，播放会有明显卡顿，如果将视频下载连接加入视频播放器中播放时又表现的很流畅。
> 
> 网页对大文件播放不够良好吗？还是什么原因...

把视频播放换Dplayer试试，不用html5的

**Comment by FFFcat** [comment]
> > 5G多的视频文件，播放会有明显卡顿，如果将视频下载连接加入视频播放器中播放时又表现的很流畅。
> > 网页对大文件播放不够良好吗？还是什么原因...
> 
> 把视频播放换Dplayer试试，不用html5的

咋换呀
