### ISSUE TITLE
虚拟主机每隔一天打开都是白屏，能不能添加一个手动刷token的按钮？

### ISSUE THREAD

**Issue by SelfEnough** [donwa/oneindex#286]
类似跟重置缓存和清空缓存一样，因为用的虚拟主机搭建的，没有能力后台设置自动刷token。
导致每次打开网站基本都是白屏，没有列表，得自己手动进后台清空全部缓存再重置缓存后才行。

**Comment by donwa** [comment]
有计划做web刷新和计划任务功能，等有时间来更新。

**Comment by fightx** [comment]
t我也存在这个问题，是不是token需要重新获取？

**Comment by pengbo0708** [comment]
希望尽早做出来，但是我们无法设置后台，所以还是希望直接在程序里附加，不用我们手动设置了，或者加个刷新token的按钮

**Comment by pengbo0708** [comment]
我们用不了php命令，只能靠您更新了 @donwa

**Comment by SomeBottle** [comment]
> 我们用不了php命令，只能靠您更新了 @donwa

donwa已经几乎不怎么维护这个项目了，若出现问题只能另请高明或者换另一个程序用.
