### ISSUE TITLE
关于ju.tn 跳转

### ISSUE THREAD

**Issue by WangNingkai** [donwa/oneindex#288]
donwa 大 oneindex 的回调 ju.tn 中转跳转是怎么实现的呢？想不明白

**Comment by donwa** [comment]
用那个deeplink来回调的，redirect_url必须为https或者是localhost。
所以对于http的连接，我用https://ju.tn做了个302跳转。

**Comment by WangNingkai** [comment]
@donwa deeplink不太了解，不过这样很强大啊😯
