### ISSUE TITLE
优化&建议

### ISSUE THREAD

**Issue by vircloud** [donwa/oneindex#29]
感谢贡献如此强大的工具！

优化：

- 开启每个目录或文件，css/js 都会重新加载一遍，不会使用已缓存的文件，此处看看能否实现优化，比如 Ajax？
- 增加访问控制，比如某个文件夹要求输密码才能访问

建议：

- 现在已经支持视频了，建议也增加对音乐的在线播放支持。

**Comment by donwa** [comment]
1、css/js 都是调用cdn的，正常不会每次都请求，本地会有缓存。

2、访问密码有计划要做，但要先写后台，有点懒，看时间。

3、音频也看时间。

近期以修复bug为主

**Comment by donwa** [comment]
@vircloud 已支持音频在线播放

**Comment by vircloud** [comment]
感谢大佬！
