### ISSUE TITLE
无法获取onedrive文件列表

### ISSUE THREAD

**Issue by kohyzsc123** [donwa/oneindex#294]
使用一周了，今天晚上发现重新刷新缓存无法获取文件列表，显示为空白目录，进入控制台重建缓存时间比平常稍长，显示重建缓存成功。查看cache目录下缓存文件内容如下：
```
<?php return array (
  0 => 1539538268,
  1 => 
  array (
  ),
);
```

请问有遇到的朋友吗？如何解决？

**Comment by chaoqing** [comment]
Same there

**Comment by taotaolin** [comment]
尝试使用 php 5.6。。我是这样解决问题了

**Comment by kohyzsc123** [comment]
> 
> 
> 尝试使用 php 5.6。。我是这样解决问题了

谢谢回复，今天下午我重置了一次服务器重新安装现在可以了。

**Comment by LineSoftteam** [comment]
我也遇到了，刚装上没问题，然后过一段时间就无法加载列表😭

**Comment by LineSoftteam** [comment]
> > 我也遇到了，刚装上没问题，然后过一段时间就无法加载列表sob
> 
> 添加计划任务了吗？

没添加，不过那个不是可选的吗

**Comment by taotaolin** [comment]
> > > 我也遇到了，刚装上没问题，然后过一段时间就无法加载列表sob
> > 
> > 
> > 添加计划任务了吗？
> 
> 没添加，不过那个不是可选的吗

我添加了。。偶尔好像也会没有东西

**Comment by LineSoftteam** [comment]
> > > > 我也遇到了，刚装上没问题，然后过一段时间就无法加载列表sob
> > > 
> > > 
> > > 添加计划任务了吗？
> > 
> > 
> > 没添加，不过那个不是可选的吗
> 
> 我添加了。。偶尔好像也会没有东西

对我也是这样，怎么办😭
