### ISSUE TITLE
gif前端访问会404

### ISSUE THREAD

**Issue by polarcn** [donwa/oneindex#30]
https://node1.ci.mk/Pictures/992009827/

这个目录下

**Comment by donwa** [comment]
配置问题，参考
https://github.com/donwa/oneindex/issues/14

**Comment by polarcn** [comment]
配置修改了也无效，依旧404

**Comment by polarcn** [comment]
![screenshot_2018-04-17-22-00-27](https://user-images.githubusercontent.com/25342559/38874516-d94938de-428a-11e8-8654-db9dd081f5d0.png)
这是配置文件

**Comment by donwa** [comment]
肯定是nginx配置问题，检查配置，重启nginx

**Comment by donwa** [comment]
/502.html 后面那一段都删掉试试。
肯定是你配置问题。

**Comment by polarcn** [comment]
终于修好了😭
