### ISSUE TITLE
忘记client secret怎么办？

### ISSUE THREAD

**Issue by ntsilverwing** [donwa/oneindex#303]
申请网盘后没印象有弹出过这东西，然后在绑定时没提示“应用机密”，直接就到快速启动了……

**Comment by meooa** [comment]
我的应用中可以重新生成新的

**Comment by xsinger** [comment]
打开这个网址https://apps.dev.microsoft.com/#/appList

里面会列出oneindex的应用，点击进去后，会看到你的应用ID（client_ID）。

找到【应用程序机密】，点击【生成新密码】，就会生成一个新的client_secret，然后重新安装时候填这个新的client_secret就可以了

**Comment by ntsilverwing** [comment]
已解决，谢谢！
