### ISSUE TITLE
我卡在API验证那里，直接跳到id页

### ISSUE THREAD

**Issue by medsonk** [donwa/oneindex#306]
我卡在API验证那里。网上有动图是点完蓝色按钮，先到key页，再到id页。我是直接跳到id页。
环境是已有lmnp，php5.6.xx，在Nginx里配一个vhost，指向oneindex目录。curl开不开都一样结果，试了两个不同全局的onedrive都一样。

**Comment by qinvz** [comment]
其实可以先复制ID，然后去my apps 页面创建serect，绑定出错就多试几次

**Comment by medsonk** [comment]
> 其实可以先复制ID，然后去my apps 页面创建serect，绑定出错就多试几次
@qinvz 刚好你发出来之前已经解决，也是这样做的。
