### ISSUE TITLE
三种缓存类型哪种好？

### ISSUE THREAD

**Issue by xsinger** [donwa/oneindex#307]
如题，我用secache的话，清除所有页面缓存，页面并没有立刻有变化，需要等待很长时间才可以显示最新的列表。

用filecache的话，清除所有页面缓存，页面马上就有变化。

**Comment by chafer516** [comment]
同问。

**Comment by Mydong** [comment]
我现在也用filecache，第一个的话不仅，不会立即变化，添加的README.md文件还显示乱码，但是filecache则不会。

**Comment by donwa** [comment]
修复了一下secache，可以再试试。

secache是以文件模拟memcache，比filecache的有事在于不会生成多文件。如果onedrive的文件和目录不多，可以使用filecache，如果比较多可以尝试secache。追求性能可以使用memcache，当然得服务器支持memcache。

**Comment by xsinger** [comment]
感谢，测试了一下，感觉没问题了~~
