### ISSUE TITLE
后台管理=>文件展示设置=>Dplayer 视频(video)如何使用？

### ISSUE THREAD

**Issue by louis9527** [donwa/oneindex#314]
Dplayer 视频(video) ，这个选项有什么用途？或者说，这里应该填写什么？

**Comment by a398496800** [comment]
默认mp4等等的文件均是html5，如果你想用Dplayer作为你网盘的播放器的话。就加上对应的扩展名,比如填上mp4，那么MP4的文件就都会用Dplayer作为播放器播放视频。

**Comment by louis9527** [comment]
嗯嗯，明白了。谢谢
