### ISSUE TITLE
密码功能无效

### ISSUE THREAD

**Issue by 9E307** [donwa/oneindex#33]
更新到最新版后，在linux系统中直接创建不带文件名的.password文件，并且写入1234当做密码，进入文件夹输入1234无反应。而设置文件名如mm.password并且写入1234当做密码，则密码功能无效，请问如何解决？

**Comment by donwa** [comment]
1、.password 内容为明文密码，不要有回车空格。
2、清楚本地缓存。

**Comment by donwa** [comment]
参考：[.password](https://raw.githubusercontent.com/donwa/oneindex/files/.password)
