### ISSUE TITLE
添加.password 输入密码无反应

### ISSUE THREAD

**Issue by mikupa** [donwa/oneindex#34]
emmm... 设置了6位数密码，对比了密码文件大小也是6字节绝对错不了，但是输入密码压根无法进入目录。

**Comment by donwa** [comment]
1、.password 内容为明文密码，不要有回车空格。
2、清楚本地缓存。

**Comment by donwa** [comment]
参考：[.password](https://raw.githubusercontent.com/donwa/oneindex/files/.password)

**Comment by eko133** [comment]
这个文件放在根目录确实没反应，只能放在文件夹内

**Comment by mikupa** [comment]
我确定密码为明文并且没有多余的空格或回车，这点可以从文件大小看出，6个密码字符文件大小就是6字节没有错，本地缓存也已经清空，可输密码还是没反应。文件不管放置在根目录还是二级目录都不管用。

**Comment by donwa** [comment]
@mikupa 我无法复现，你没更新代码吧？

**Comment by vircloud** [comment]
估计一样的权限问题，参考 https://github.com/donwa/oneindex/issues/43

**Comment by clcaal** [comment]
我也出现这个问题了，前几天都正常，这几天怎么输入密码都没反应
