### ISSUE TITLE
多级目录设置密码问题

### ISSUE THREAD

**Issue by 9uest** [donwa/oneindex#380]
#65 这里虽然说是特性，不是bug 
但是这种设计那目录弄个密码还有意义吗？

通过一级一级往上翻 只要不到密码所在的目录，下面的目录都可以查看到

临时解决是  每个目录下都放个.password  

但是输入密码输的手累诶

**Comment by 9uest** [comment]
> 但是一个目录下面全部文件访问加密不也回很麻烦？你想想外链调用咋办呢？
> 这个对外链的调用还是很舒服的，如果想防止翻目录，可以在那个保护的目录下面加一个index.html

是啊，子目录每个目录输入密码也很麻烦，index.html提议不错。   不知道如果参考百度网盘分享那种会不会好点，不过应该很麻烦 代码

**Comment by 9uest** [comment]
index.html 试过 效果不行，谁都看不到目录文件结构了，包括我

**Comment by Riajyuu** [comment]
I agreed with @9uest
it is really stupid to make password easily bypassed by browsing history.

**Comment by Riajyuu** [comment]
@xtgjzwj
401 HTTP code and cookies will work here

**Comment by a398496800** [comment]
这个问题貌似只要在第三个风格才会出现这个问题，我现在是在每个目录下直接判定cookie，cookie不成立就直接跳转回首页。每次输入密码后会设置一个当前路径md5的一个cookie 你参考一下就OK了。
