### ISSUE TITLE
新版文件夹中文件数量很多时生成列表错误（404或空白）

### ISSUE THREAD

**Issue by asiacny** [donwa/oneindex#39]
新版当根目录中一个文件夹数量有11000多（更大也一样），直接打开前端目录时显示404，用php cli生成缓存大小只有65B，并无报错，同时生成的其他文件夹显示正常，以下是生成的65B文件：（旧版3月31日版正常生成查看）
php return array (
  0 => 1524121730,
  1 => 
  array (
  ),
);

**Comment by donwa** [comment]
一次请求最多好像获取100个文件，11000个文件，得请求100多次，不出错也爆内存啊。

**Comment by asiacny** [comment]
这样哦，但旧版没任何问题哇，目前树把cache目录和config目录软连接到旧版目录，用php cli定期更新旧版，再用新版查看的

**Comment by asiacny** [comment]
刚测试了下，性能还不错，旧版更新时内存不超过100m，cpu不超过20%，11000数量的目录生成缓存16M大小，偶尔会弹出以下错误（PHP Warning:  array_merge(): Argument #2 is not an array in /home/wwwroot/default/onedrive/lib/onedrive.php on line 105），新版无任何提示且内存不超过30M

**Comment by donwa** [comment]
新版本增加缩略图获取，获取数据会大非常多。几百次请求出现一次请求失败就会报【PHP Warning: array_merge():】(刚更新了下，缓解了这个问题。)。

多文件在一个文件夹中，非常影响性能，我也没办法。

**Comment by asiacny** [comment]
ok！那我继续用旧版更新缓存，希望老大在问题没解决前能让旧版的缓存文件与新版一直兼容

**Comment by donwa** [comment]
重新优化了下缓存逻辑和大小，你再试试吧。

其实早就不兼容了，你用老的缓存，缩略图是出不来的。
