### ISSUE TITLE
突然空白~

### ISSUE THREAD

**Issue by a398496800** [donwa/oneindex#391]
是的，两个网盘 突然就变成了空白，文件不展示了。难受，其中一个已经换成了pyone并已经可以显示。但是这一个我还想拯救一下，起码得知道是什么问题吧。。。有没有老司机

**Comment by donwa** [comment]
重新装一遍程序试试。不行就重新装两遍。

**Comment by a398496800** [comment]
> 重新装一遍程序试试。不行就重新装两遍。

经过三台小鸡，三个域名的测试。可以肯定死于onedrive之手，不过不知道为什么PYONE能加载。。。迷，不过PYone不好用。。。。。

**Comment by 29969343** [comment]
我的也不行了.....

**Comment by donwa** [comment]
我本地测试都是正常的，估计和账号有关系。你可以试试用个人账号试试，不要用企业（教育）账号。

**Comment by Quartercn** [comment]
我也是，今天突然暴毙，好几个都直接挂了

**Comment by a398496800** [comment]
> 我本地测试都是正常的，估计和账号有关系。你可以试试用个人账号试试，不要用企业（教育）账号。

是的，可以确定是账号的问题了。。100% 就是不知道能不能好了。

**Comment by Quartercn** [comment]
哦对了，另外一个问题是onedrive的web端也是登不上了，页面都加载不出来

**Comment by 29969343** [comment]
你们有用pyone可以的？确定么？不行我先换成PYONE吧

**Comment by 29969343** [comment]
你们有用pyone可以的？确定么？不行我先换成PYONE吧

**Comment by Quartercn** [comment]
> 你们有用pyone可以的？确定么？不行我先换成PYONE吧

不知道，没有试，不是很喜欢pyone

**Comment by a398496800** [comment]
> 你们有用pyone可以的？确定么？不行我先换成PYONE吧

别，我第二个就不行。这个很难说 但是你可以试试 不是就重来吧。。我已经重来了

**Comment by kfangf** [comment]
emm我也是的呢，可能是API改了吧qwq

**Comment by sdshdv** [comment]
卧槽,我的三个网盘也全空白了

**Comment by wxlost** [comment]
我的也空白了...蛋疼了

**Comment by Quartercn** [comment]
> 确实这样..建议把v2版本的api加上...现在估计使用个人版的也不多

v2版本的api是...

**Comment by lb19921021** [comment]
今天突然就不能用了   难道是微软限制了？

**Comment by ShallowAi** [comment]
全白了......

**Comment by Quartercn** [comment]
手动测试请求： Status  429 Too Many Requests

**Comment by sdshdv** [comment]
目前暂时换成pyone了，暂时情况良好,希望oneindex作者尽快修复问题

**Comment by kfangf** [comment]
嗯，作者失踪了qwq 我找个时间研究下（文档在哪啊qwq）
不想用PyOne 我的破机器估计带不动

**Comment by Zxilly** [comment]
全白了，目测挂了

**Comment by czy0409** [comment]
测试了一下，个人账户可以，教育版账户不行了，看作者能不能搞定了....教育版有1个T啊~

**Comment by liehuolianyu** [comment]
退回2.0版本可以显示了

**Comment by a398496800** [comment]
> 退回2.0版本可以显示了

2.0是啥子版本

**Comment by xhwsd** [comment]
哈哈，我的1个/个人，1个/教育 也白了，是不是官方API更新或限制了~

**Comment by czy0409** [comment]
@donwa version2可以正常使用教育版的账户，新版本不行，求修复😀

**Comment by Quartercn** [comment]
亲测version2可以使用，我来分析一下区别是什么

**Comment by 29969343** [comment]
我换回oneindex2.0版本了，可用了。文件读取没问题
但是HEAD无法显示，密码也不支持....
哪位大神找到原因改好了，给个消息啊！29969343@qq.com

**Comment by a398496800** [comment]
受到各位2.0的启发，然后我发现2.0其实是用的作者的应用程序授权，所以不会出现空白。那么修改的方式也很简单，当然，这里修改的是最新的那个版本。下面放过程
首先，你需要找到2.0 config\base.php 这个文件的应用程序授权信息，如下面

<?php return array (
  'client_id' => 'ea2b36f6-b8ad-40be-bc0f-e5e4a4a7d4fa',
  'client_secret' => 'EIVCx5ztMSxMsga18MQ7rmGf9EIP7zv6tfimb0Kp5Uc=',
  'redirect_uri' => 'https://ju.tn/onedrive-login',
  'onedrive_root'=> '', //onedrive中要共享的目录，默认为根目录，可以改成如: /share
  'cache_type'=> 'file',//sqlite 需要pdo 支持
  'cache_expire_time' => 3600,
  'cache_refresh_time' => 600,
  'root_path' => '?'
);
然后将该文件复制到3.0同样的目录下，如果有请删除在复制，然后修改controller\AdminController.php
在其中找到https://ju.tn/ 修改为https://ju.tn/onedrive-login，然后将程序整个重新安装，安装的过程一直下一步，不用获取应用信息，然后绑定账号即可。亲测成功，祝你们好运。。
另外，我估计作者的这个授权可能会被玩坏，就跟我们一样~

**Comment by a398496800** [comment]
> 受到各位2.0的启发，然后我发现2.0其实是用的作者的应用程序授权，所以不会出现空白。那么修改的方式也很简单，当然，这里修改的是最新的那个版本。放下面过程
> 首先，你需要找到2.0 config \ base.php这个文件的应用程序授权信息，如下面
> 
> 'ea2b36f6-b8ad-40be-bc0f-e5e4a4a7d4fa'，'client_secret'=>'EIVCx5ztMSxMsga18MQ7rmGf9EIP7zv6tfimb0Kp5Uc ='，'redirect_uri'=>'https://ju.tn/onedrive-login'，'onedrive_root'=>''，/ / onedrive中要共享的目录，默认为根目录，可以改成如：/ share'cache_type'=>'file'，// sqlite需要pdo支持'cache_expire_time'=> 3600，'cache_refresh_time'=> 600，' root_path'=>'？' ）; 然后将该文件复制到3.0同样的目录下，如果有请删除在复制，然后修改controller \ AdminController.php在其中找到https://ju.tn/修改为https://ju.tn/onedrive-login ，然后将程序整个重新安装，安装的过程一直下一步，不用获取应用信息，然后绑定账号即可。亲测成功，祝你们好运..另外，我估计作者的这个授权可能会被玩坏，就跟我们一样〜

原理就是，不使用自己的应用程序授权。用作者的~

**Comment by imrsp** [comment]
照你说的做了，仍然空白，但2.0依然可以使用

**Comment by a398496800** [comment]
绝望.jpg，2.0我能显示，但是所有视频均无法下载，无法显示。废了 废了。。。难受啊，能显示也没用 难受~

**Comment by a398496800** [comment]
> 绝望.jpg，2.0我能显示，但是所有视频均无法下载，无法显示。废了废了...难受啊，能显示也没用难受〜

好了，把自己玩坏了 oneindex跟pyone生成的下载链接均不可访问，但可读取文件夹。凉凉洛 再见~

**Comment by imrsp** [comment]
无法使用，请问怎么办呢？

**Comment by ddkk3000** [comment]
> 无法使用，请问怎么办呢？

你把缓存的时间设置长一些就行了

**Comment by zhiiker** [comment]
一样的情况，应该是API调用次数的限制
