### ISSUE TITLE
redis的缓存过期时间为什么是个很大的值？

### ISSUE THREAD

**Issue by bafflingbug** [donwa/oneindex#406]
不太明白为什么是 time()+$expire

**Comment by Rhilip** [comment]
（不只是Redis，所有的cache引擎设置的缓存过期时间都是极大值2333

**Comment by bafflingbug** [comment]
> （不只是Redis，所有的cache引擎设置的缓存过期时间都是极大值2333

所以说是出于什么考虑做这种设计？

**Comment by jianhua0209** [comment]
为什么我的不能用？

**Comment by bafflingbug** [comment]
> 为什么我的不能用？

@jianhua0209 应该是合并多个pr时候出了问题。貌似现在已经修复了。更新下代码试试

**Comment by jianhua0209** [comment]
我手动在后台添加了，使用后报错。

**Comment by XiaoPika** [comment]
同楼上，更新代码后在admin选择缓存为redis后选择清除缓存和重建缓存直接显示HTTP 500

**Comment by bafflingbug** [comment]
> 同楼上，更新代码后在admin选择缓存为redis后选择清除缓存和重建缓存直接显示HTTP 500
@XiaoPika @jianhua0209 确定已经安装了`redis`和`php的redis扩展`？

**Comment by isecret** [comment]
在启用 memcache 和 redis 为缓存的时候确实应该先判断是否存在这个环境。
