### ISSUE TITLE
添加 .password 后 500 错误

### ISSUE THREAD

**Issue by vircloud** [donwa/oneindex#43]
如题，添加 .password 后 500 错误，删除 .password 又出现解密界面，对 .password 文件有要求吗？我是在 linux 下直接 vim 生成的 .password

**Comment by donwa** [comment]
https://github.com/donwa/oneindex/tree/files

**Comment by vircloud** [comment]
我是放在 OneDrive 要加密的文件夹里，比如要加密 /Movie/，用你链接里的 .password 文件，就执行 php one.php upload:file .password /Movie/，然后刷缓存 php one.php cache:refresh，打开 Movie 页面就 500 了

**Comment by donwa** [comment]
去掉 init.php 中的`error_reporting(E_ALL & ~E_NOTICE);`，看看具体哪一行报错。

**Comment by vircloud** [comment]
直接抛出 500 异常，没有错误提示，怀疑是在取密码时出错

**Comment by donwa** [comment]
应该是你的环境禁止了异常详情显示。找找log吧，没有错误详情，我调不了

**Comment by vircloud** [comment]
若直接指定 $password = '1234'; 可以工作

**Comment by donwa** [comment]
这个不是致命错误，不应该是这个问题。

**Comment by vircloud** [comment]
服务器配置重新检查了下，我了个去，发现错误了，“ **设置config/、config/base.php 、 cache/ 可读写**” ，设置成 755 不够，要 777 才可以~~~~~~~

**Comment by vircloud** [comment]
是的，生成 sqlite,token.php 都没有报错
