### ISSUE TITLE
提交几个bug。

### ISSUE THREAD

**Issue by sanshuifeibing** [donwa/oneindex#431]
**使用的是项目目前最新的代码。**

# 环境:  

- 宝塔面板
- CentOS 7.5
- Ngnix 1.15
- PHP 7.2

# Bug  

1. `.password`设置无效，无限循环密码输入页面。
2. `README.md`无法显示。
3. `HEAD.md`无法显示。
4. `.txt`文本无法直接输出。
5. `index.html`网页无法直接输出。
6. `文本/代码(code)`下所有的后缀，都无法输出。

**Comment by geekglasshouse** [comment]
请问你是不是把这些文件都放服务器了？

**Comment by nmdx** [comment]
这都说明一个问题  你的服务器与解析出来的直链连接拉取数据出现了问题

**Comment by sanshuifeibing** [comment]
> 这都说明一个问题 你的服务器与解析出来的直链连接拉取数据出现了问题

那为什么只有新代码才出这个问题呢？

**Comment by nmdx** [comment]
> > 这都说明一个问题 你的服务器与解析出来的直链连接拉取数据出现了问题
> 
> 那为什么只有新代码才出这个问题呢？

这我就不知道啦，目前只能确认这大概是curl的问题，可以对比下你的两个版本之间的commits https://github.com/donwa/oneindex/issues/384#issuecomment-4516677

**Comment by sanshuifeibing** [comment]
> > > 这都说明一个问题 你的服务器与解析出来的直链连接拉取数据出现了问题
> > 
> > 
> > 那为什么只有新代码才出这个问题呢？
> 
> 这我就不知道啦，目前只能确认这大概是curl的问题，可以对比下你的两个版本之间的commits [#384 (comment)](https://github.com/donwa/oneindex/issues/384#issuecomment-4516677)

对于php等网页编程语言我不太懂，只能弱弱做个使（shen）用（shou）者（dang）了，不过还是很感谢你的回复。目前已用回旧代码，除了md无法显示以外，其他情况都正常。不过期间我有试过OLAIndex和PyOne等同类产品，都没有这些问题，建议可以参考一下它们的这部分代码。
