### ISSUE TITLE
about code 

### ISSUE THREAD

**Issue by yyqyu** [donwa/oneindex#44]
install well, but no code to sing up?  how long i need wait?

**Comment by donwa** [comment]
Mr.Yang.
you bi xu you yi ge onedrive business zhang hao.

**Comment by gaojianye** [comment]
hao gao duan a!

**Comment by yyqyu** [comment]
需要注册，如何获取那个邀请码呀？

**Comment by yyqyu** [comment]
我有onedrive bussiness 账号，就是卡在注册哪里了

**Comment by donwa** [comment]
不用注册，点击绑定账号，登录你的账号，程序就验证成功了。

**Comment by platoer** [comment]
域名没有验证的原因，有账户不代表有账户api的权限，之前我也遇到过:)

2018-04-21 21:58 GMT+08:00 donwa <notifications@github.com<mailto:notifications@github.com>>:

不用注册，点击绑定账号，登录你的账号，程序就验证成功了。

**Comment by yyqyu** [comment]
ok了，之前的域名有问题 解析到其他位置去了
