### ISSUE TITLE
onedrive-login问题

### ISSUE THREAD

**Issue by fl20002** [donwa/oneindex#45]
新建了一个文件onedrive-login放在根目录

安装时为啥输入账号密码后就是下载这个文件？

**Comment by donwa** [comment]
https://github.com/donwa/oneindex/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E8%87%AA%E5%B7%B1%E7%9A%84client_id%E3%80%81client_secret

**Comment by fl20002** [comment]
回复URL怎么填写？

**Comment by vircloud** [comment]
参考：https://blog.vircloud.net/media/oneindex.html
