### ISSUE TITLE
密码文件夹的判断逻辑，直接访问二级文件夹可跳过密码验证

### ISSUE THREAD

**Issue by joeyliu6** [donwa/oneindex#461]
在一级文件夹设置密码后，若是直接访问二级文件夹是不需要密码的。

我在`文档`这个文件夹设置了密码，当我分享一个链接给别人后，如
```html
https://pan.domain.com/文档/学习资料/example.doc
```
可能会有有心人访问
```html
https://pan.domain.com/文档/学习资料
```
那么`学习资料里`我不想让别人知道的文档都可以被有心人获取。

为保其他资料的安全性，是否可以添加一个功能：为一级文件夹设置密码后，访问子文件夹时也需要密码验证。

另附：在 #363 曾提到 OneIndex 密码逻辑确实是这样的，可我自己测试后无需密码即可访问。

无需密码（从谷歌搜出来的）：https://drive.529i.com/girlimg%E5%AF%86%E7%A0%81123/%5BBoLoLi%5D%20Vol.065%20%EB%AF%BC%EA%B2%BD%20Part%201%20%5B25P%5D/

需要密码：https://drive.529i.com/girlimg%E5%AF%86%E7%A0%81123

**Comment by bafflingbug** [comment]
如果我没有理解错代码的话，你描述的现象是符合代码预期结果的。你提到的另一个issues说的是另一个问题：由于某种原因导致程序不能正确读到`.password`里面的内容，所以一直提示密码出错。

你期望的功能我也考虑过，看现在的实现方式并不是向windows那样从最外层一层层的去访问，而是直接访问请求的文件夹。如果要是在现有代码的基础上实现的话，我能想到的办法就是递归查找父文件夹是否有`.password`文件。如果文件夹层数过多，感觉请求的总时间是无法接受的。

最后，附上我现在的解决办法。是在每个子文件夹都拷贝一份`.password`文件

**Comment by joeyliu6** [comment]
嗯嗯，好的，谢谢你的回答。我之前想的也是这个解决方法，稍微有些麻烦。
