### ISSUE TITLE
首次绑定提示登陆时遇到问题，在次绑定显示程序安装失败，请问问题出在哪里

### ISSUE THREAD

**Issue by ZQ-Qi** [donwa/oneindex#476]
第一次绑定时获取到机密和ID后，进入账号绑定，点击链接微软提示（浏览器仅登陆该微软账户，无其他账户在线，且更换浏览器无效）：

> 抱歉，登录时遇到问题。
> AADSTS700016: Application with identifier 'b4d66e23-2c01-4786-9878-ea22006f231c' was not found in the directory '9976252b-9a4b-4f2b-8273-39ccd5dc40c0'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant

再次利用该机密和ID进行绑定，弹出微软登陆页面选择该已登录账户后即跳转，得到提示程序安装失败。

请问这个问题如何解决？

**Comment by ZQ-Qi** [comment]
中间跳转页的URL存在报错信息：

> https://oneindex.github.io/?error=invalid_client&error_description=AADSTS650051:+Using+application+'oneindex'+is+currently+not+supported+for+your+organization+stu.xidian.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+stu.xidian.edu.cn+before+the+application+oneindex+can+be+provisioned.+Request+ID:+fa57eba6-214f-4758-ba9c-1b1dd195~~~~,+Timestamp:+02/12/2019+10:48:07
> Trace+ID:+b258bcde-0d16-4d1f-8e4e-c7c8fffd~~~~
> Correlation+ID:+c5e2f6a0-7701-48cd-a58b-e07b9433~~~~
> Timestamp:+2019-02-12+10:48:07Z&state=http://www.~~~~.tk/

但是我没有找到方法来解决这个问题

**Comment by gzelvis** [comment]
我也遇到了这个问题，同求解决办法

**Comment by Winyer** [comment]
#471

**Comment by bafflingbug** [comment]
可以尝试再次建立一个App，获取新的机密和ID。
可以在[这里](https://apps.dev.microsoft.com/#/appList)删除原有的App。

建议第一次绑定时候新建App的和绑定网盘的使用同一个账户

----

看错误信息，貌似和 #443 一致。但是并不确定。如果学校确实封禁了Oneindex且禁止绑定第三方App的确无解。如果没有禁止绑定的话，可以在[这里](https://apps.dev.microsoft.com/#/appList)手动新建App，名称不要用OneIndex或近似名称。
具体方式是`生成新密码`获取机密,`添加平台`选`web`重定向url填`https://oneindex.github.io/`

**Comment by Rhilip** [comment]
@bafflingbug 不与 #443 一致，此处错误提示是 
```
AADSTS650051:+Using+application+'oneindex'+is+currently+not+supported+for+your+organization+stu.xidian.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+stu.xidian.edu.cn+before+the+application+oneindex+can+be+provisioned.
```
意思是域没有管理员，所以不能使用第三方APP。（国内很多大学的edu邮箱申请OneDrive 1T基本都这样）
#443 的是域有管理员，但是管理员限制使用未经授权的第三方APP。

**Comment by T1me** [comment]
你可以使用个人帐号注册APP，但在oneindex安装时绑定edu帐号

**Comment by tolache** [comment]
>您需要能夠修改DNS記錄以向MS進行身份驗證

我該怎麼辦？

**Comment by lzkgbld** [comment]
我想问一下，我的是直接绑定账户之后，跳转就挂了，无法访问此网站，意外终止了连接，这是怎么回事？
