### ISSUE TITLE
点击链接：绑定账户  404

### ISSUE THREAD

**Issue by iJayscn** [donwa/oneindex#48]
点击链接：绑定账户 

跳转到：https://域名/&code=XXX   页面显示 404

手动调整为：https://域名/?/install&code=XXX  502 Bad Gateway

手动调整为：https://域名/?/&code=XXX  认证失败

client_id
client_secret
redirect_uri

三个参数都正常，也能获取到code！

**Comment by vircloud** [comment]
建议检查下 Nginx/Apache 配置，特别是重写这块

**Comment by iJayscn** [comment]
本机 windows + apache  调试也是 无法绑定！ 但是client_id、client_secret、code 都可以获取到
![localhost-oneindex](https://user-images.githubusercontent.com/7768188/39171426-555c712a-47d1-11e8-81a7-6bd5de1d250a.png)

**Comment by donwa** [comment]
onedrive 根目录文件太多了。

**Comment by iJayscn** [comment]
@donwa  首页文件不多啊，而且 我也建立了个share文件夹测试了  还是一样
![oneindex-index](https://user-images.githubusercontent.com/7768188/39172270-d2b114bc-47d3-11e8-92bc-c8981734fc29.png)

**Comment by donwa** [comment]
那就看看你的 config/base.php 中 app_url。应该是访问你的app_url访问不到。

**Comment by iJayscn** [comment]
@donwa config/base.php 中 app_url ?  没有这个参数啊？   还是 你是指 Azure 的 应用程序 ID URI

**Comment by donwa** [comment]
那就是绑定不成功。

**Comment by iJayscn** [comment]
@donwa 请问，那是不是因为 Azure 的 应用程序 ID URI 这个地址 无法访问，导致的绑定失败？

**Comment by donwa** [comment]
你要换client_secret就一步一步按说明去搞，已经很详细了，不再具体解释。
