### ISSUE TITLE
空白页！令牌已刷新，缓存已经重建！

### ISSUE THREAD

**Issue by 91en** [donwa/oneindex#493]
空白页！令牌已刷新，缓存已经重建！服务器已经重启！PHP版本尝试过更换！已经尝试重装！  
仍然空白！  
![tim 20190221122313](https://user-images.githubusercontent.com/37232901/53143609-b0144200-35d3-11e9-965b-7d34a101764a.png)  

![b 7 k99 wmo2 8cs2f5hg](https://user-images.githubusercontent.com/37232901/53143511-4300ac80-35d3-11e9-8ff1-3706f98c6b0d.png)  
请问还能怎么解决？

**Comment by PikachuCN** [comment]
我今天也这样子。第一次用，刚还能显示，后来就变空白页了

**Comment by iqiqiya** [comment]
一样一样的  解决了吗

**Comment by 91en** [comment]
没解决！

**Comment by 91en** [comment]
> 一样一样的 解决了吗

没解决

**Comment by chongqidewawa** [comment]
这个重装可以解决，我试过了，另外重装的话不影响图床链接

**Comment by liehuolianyu** [comment]
将自己的网站改成https的，再在重定向url填入自己的域名，即可解决

**Comment by PikachuCN** [comment]
> 将自己的网站改成https的，再在重定向url填入自己的域名，即可解决

重定向URL哪里填入？我记得安装的时候是默认改不了

**Comment by iqiqiya** [comment]
可以试试重新获取并修改应用 ID(client_id)和应用机密(client secret)
查看这里：https://github.com/iqiqiya/oneindex/blob/master/README.md

**Comment by liehuolianyu** [comment]
> > 将自己的网站改成https的，再在重定向url填入自己的域名，即可解决
> 
> 重定向URL哪里填入？我记得安装的时候是默认改不了

在config目录下的base.php里面有redirect_uri，把这个改成你的域名，再去https://apps.dev.microsoft.com 这个里面找到你的应用，把重定向 URL改成你的域名，最后重建缓存即可
有个要注意的，安装的时候网站得是http的，要不然安装失败，安装完成之后如果没有目录结构，再把你的网站改成https的，按照上面的步骤操作，就可以了

**Comment by PikachuCN** [comment]
> > > 将自己的网站改成https的，再在重定向url填入自己的域名，即可解决
> > 
> > 
> > 重定向URL哪里填入？我记得安装的时候是默认改不了
> 
> 在config目录下的base.php里面有redirect_uri，把这个改成你的域名，再去https://apps.dev.microsoft.com 这个里面找到你的应用，把重定向 URL改成你的域名，最后重建缓存即可
> 有个要注意的，安装的时候网站得是http的，要不然安装失败，安装完成之后如果没有目录结构，再把你的网站改成https的，按照上面的步骤操作，就可以了

你好，我按照您的做法，也重装了，但是依旧无法显示
https://file.dengzile.com/ 依旧定期会显示空白文件页面。

**Comment by sgl666** [comment]
一样

**Comment by sgl666** [comment]
> > > > 将自己的网站改成https的，再在重定向url填入自己的域名，即可解决
> > > 
> > > 
> > > 重定向URL哪里填入？我记得安装的时候是默认改不了
> > 
> > 
> > 在config目录下的base.php里面有redirect_uri，把这个改成你的域名，再去https://apps.dev.microsoft.com 这个里面找到你的应用，把重定向 URL改成你的域名，最后重建缓存即可
> > 有个要注意的，安装的时候网站得是http的，要不然安装失败，安装完成之后如果没有目录结构，再把你的网站改成https的，按照上面的步骤操作，就可以了
> 
> 你好，我按照您的做法，也重装了，但是依旧无法显示
> https://file.dengzile.com/ 依旧定期会显示空白文件页面。

一样

**Comment by PikachuCN** [comment]
现在虽然能显示，但是视频也无法播放，不知道是不是微软现在限制了。

**Comment by 91en** [comment]
换了个盘，重装解决了！也不知道是不是限制了啥！

**Comment by iqiqiya** [comment]
可以试试重新获取并修改应用 ID(client_id)和应用机密(client secret)
具体步骤可以查看这里：https://github.com/iqiqiya/oneindex/blob/master/README.md

我这边显示正常
