### ISSUE TITLE
导航栏如何把颜色改为黑颜色

### ISSUE THREAD

**Issue by sskk3334** [donwa/oneindex#498]
![28fca325bd34f71914e0d8d3a6ec19c](https://user-images.githubusercontent.com/44055943/53644948-c7f26280-3c72-11e9-90e8-1af704b8fda7.jpg)

有没有人能教下怎么修改

**Comment by wyj20050211** [comment]
oneindex主目录下
/view/material/layout.php中
body的类"mdui-theme-primary-blue-grey"
改为"mdui-theme-primary-black"

**Comment by sskk3334** [comment]
![snipaste_2019-03-03_10-08-05](https://user-images.githubusercontent.com/44055943/53689964-57476500-3d9c-11e9-8b92-2607cf682f5b.png)
![snipaste_2019-03-03_10-11-16](https://user-images.githubusercontent.com/44055943/53689981-bb6a2900-3d9c-11e9-94cc-7904a272b3da.png)
我改过之后，导航栏背景颜色白色，字体变黑色。 我想要的字体白， 导航栏背景为黑色。
是我改错哪里吗，请大家教教我下

**Comment by wyj20050211** [comment]
mdui开发文档https://www.mdui.org/docs/
主题色中没有黑色，你只能自己写样式
在header标签的类中，去除类名"mdui-color-theme"，添加类名"mdui-text-color-white"（让文字显示为白色），再写一个你喜欢的类名，例如"black"，在style标签中写入样式".black{background-color:#000}"，其中black是对应你在header中的类名

**Comment by sskk3334** [comment]
![snipaste_2019-03-03_11-32-37](https://user-images.githubusercontent.com/44055943/53690571-2f5dfe80-3da8-11e9-813a-5b7d98ace5f0.png)
![snipaste_2019-03-03_11-35-34](https://user-images.githubusercontent.com/44055943/53690589-87950080-3da8-11e9-8572-c5e7de77d254.png)
我照你的方法图片试了，怎么变成这样，我都懵了。你帮我看看哪里错误
你能发下你那页全部代码发给我吗 再次麻烦你了

**Comment by wyj20050211** [comment]
https://github.com/wyj20050211/demo

**Comment by sskk3334** [comment]
太感谢你了，嘻嘻，我找到原因了，我把你给的代码比对下，发现并没有问题，当时就懵B了，后来我用手机浏览器打开发现已经改变颜色了，原来是我电脑上浏览器的问题。
再次感谢你帮助，谢谢啦！

**Comment by wyj20050211** [comment]
电脑浏览器可能是优先级不同，可以把样式写在标签里作为内联样式，已经更新到我的demo里，再试试

**Comment by sskk3334** [comment]
哇！果然，完美解决，感谢感谢!!!
