### ISSUE TITLE
突然无法解析.password和README.md等文件

### ISSUE THREAD

**Issue by tylevnovik** [donwa/oneindex#503]
1.不清楚什么时候开始的
2.od文件夹里的.password，README.md，HEAD.md等文件正常（在客户端可以正常上传下载，文件并未改变）
3.oneindex无法解析并显示README.md，HEAD.md文件
4.存在.password文件的文件夹会提示输入密码，但密码一律判断错误
5.之前是正常的

**Comment by tylevnovik** [comment]
6.美国主机

**Comment by xavier-niu** [comment]
同出现这个问题

**Comment by XiaoPika** [comment]
搜索一下issues，这是一个存在了一年的问题了，换账号可以解决

**Comment by XiaoPika** [comment]
搜索一下issues，这是一个存在了半年多的问题了，貌似属于curl与https上的问题，具体原理我不太清楚，有人分析过

**Comment by XiaoPika** [comment]
https://github.com/donwa/oneindex/issues/421

**Comment by bafflingbug** [comment]
> 搜索一下issues，这是一个存在了半年多的问题了，貌似属于curl与https上的问题，具体原理我不太清楚，有人分析过

看了下描述，他们推出是ssl验证的问题，但是目前来看我在代码中发现已经忽略了ssl验证，[代码在这里](https://github.com/donwa/oneindex/blob/91b40ba6a295abb251cabe98f75e9b17ab04c25b/lib/fetch.php#L21)

虽然这句应该写为<code>CURLOPT_SSL_VERIFYHOST => 0,</code>不过应该不会影响执行把
