### ISSUE TITLE
代码不规范 颈椎两行泪 求一个apache用的伪静态.htaccess

### ISSUE THREAD

**Issue by Mosney** [donwa/oneindex#509]
前情提要#508 
排查了一晚上，终于找到问题所在...我的颈椎...
问题就出在我自己写的这段烂正则上，求好心人分享apache的伪静态URL Rewrite规则...
```
#URL Rewrite为Oneindex开启伪静态
<IfModule mod_rewrite.c>
	 RewriteEngine on
	 RewriteRule ^(.*)$ ?$1
</IfModule>
```

**Comment by wyj20050211** [comment]
#wordpress自带的就行
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

**Comment by Mosney** [comment]
@wyj20050211 感谢帮助
