### ISSUE TITLE
我在绑定微软账号的出现报错：AADSTS700016

### ISSUE THREAD

**Issue by huozk0804** [donwa/oneindex#511]
Request Id: 697cdf45-6e05-49ca-b120-10869ed41800
Correlation Id: a9b307fc-28d7-4971-8819-c9ba144d552e
Timestamp: 2019-03-29T07:01:46Z
Message: AADSTS700016: Application with identifier '89f3548d-f18d-4a5d-9deb-110ae12e41a3' was not found in the directory 'b895a31c-8bf3-437f-83b3-541ecd40e20e'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
高级诊断: 禁用
如果打算通过获取支持来解决问题，请启用此功能，并尝试重现错误。这会收集有助于排查此问题的其他信息。

**Comment by huozk0804** [comment]
已解决：F5 刷新即可

**Comment by Ro0kie** [comment]
我刷新以后 显示成功但是得不到网盘的列表啊，。，显示全是空白

**Comment by zhufengning** [comment]
刷新之后直接安装失败啊
