### ISSUE TITLE
播放器

### ISSUE THREAD

**Issue by Flysky12138** [donwa/oneindex#516]
ts格式视频播放模糊

**Comment by XiaoPika** [comment]
DASH 串流是这样的，会根据网络情况自动下调画质，改成HTML5即可

**Comment by Flysky12138** [comment]
这。。。我是在线播放的，这个怎么改html5，没看到设置选项

**Comment by XiaoPika** [comment]
![QQ截图20190413123856](https://user-images.githubusercontent.com/10910848/56074663-1efa6400-5de9-11e9-8b99-58da2f4c91a5.png)
