### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by cuijianzhuang** [donwa/oneindex#523]
为啥我搭的网盘经常一打开视频不在线播放直接下载啊？怎么解决
![Screenshot_20190419-145739](https://user-images.githubusercontent.com/31424401/56411495-8580f580-62b3-11e9-87f3-bbf813223c2b.jpg)

**Comment by XiaoPika** [comment]
确认后台设置相应后缀名是否添加到调用播放器的栏目里，如mkv格式如果没有写到HTML5或DPLAYER支持列表里就会自动下载

新建网页在网址后面加 &s=1 不会自动下载

**Comment by cuijianzhuang** [comment]
谢谢

**Comment by XiaoPika** [comment]
close please
