### ISSUE TITLE
视频不能预览，也没法下载怎么办？

### ISSUE THREAD

**Issue by Acidwits** [donwa/oneindex#527]
- 如图
![1.png](https://i.loli.net/2019/04/21/5cbc407149285.png)
![2.png](https://i.loli.net/2019/04/21/5cbc40717e890.png)
- 是onedrive那边受限制么？

**Comment by Acidwits** [comment]
不仅是视频哦，所有文件都没法下载或预览，但是通过oneindex图床上传图片是可以的，只不过也没法在MarkDown中引用……

**Comment by a398496800** [comment]
淘宝买的吧 这域真熟悉 换店铺买吧 已经废了

**Comment by Acidwits** [comment]
谢谢，但是
怎么在买之前知道买之后能不能用？
大概什么原因会导致废掉？

**Comment by a398496800** [comment]
跟你一样使用onedrive目录的用户，他们的滥用已经导致这个域完全废了。
就是那个下载地址的域名cnskk-my。
推荐买一些没啥人使用的，不要买靠前的，那些基本都已经被滥用了。

**Comment by SomeBottle** [comment]
流量过大，调用次数超常就会受限
