### ISSUE TITLE
间歇性出现Service unavailable

### ISSUE THREAD

**Issue by YuutaDoNo** [donwa/oneindex#534]
点击文件下载时，有时会出现
```
{"error":{"code":"serviceNotAvailable","message":"Service unavailable","retryAfterSeconds":30}}
```

**Comment by fxbjhc** [comment]
同问题

**Comment by Catkamakura** [comment]
同问题

**Comment by wshdliu** [comment]
同问题 重装也是这个

**Comment by yanlihu** [comment]
同问题

**Comment by yanlihu** [comment]
> 点击文件下载时，有时会出现
> 
> ```
> {"error":{"code":"serviceNotAvailable","message":"Service unavailable","retryAfterSeconds":30}}
> ```

token 和缓存频率设低一点

**Comment by bugs1998** [comment]
你们有解决这个问题了么，但是我看到这位站长的好像很稳定 http://www.jyf123.xyz/，有没有认识的去取取经
