### ISSUE TITLE
超过800k图片无法上传到图床

### ISSUE THREAD

**Issue by w2r** [donwa/oneindex#543]
低于800kb图片上传正常，超过800kb无法上传到图床，上传后重新回到上传页面，后台可以找到上传图片，但是图片部分缺失，且上传的图片大小均低于800kb，

**Comment by luochenzhimu** [comment]
不建议做图床，会出现间歇性不可访问，有流量频率限制。

**Comment by w2r** [comment]
已放弃做图床
