### ISSUE TITLE
几率解决空白页的方法

### ISSUE THREAD

**Issue by chuan01** [donwa/oneindex#544]
设置源码所在文件夹权限777。然后重启服务器。再打开域名就可以显示了。

**Comment by SomeBottle** [comment]
首先空白页和文件夹权限并没有很大关系，请进行多次测试再得出结论。  
空白页主要问题是服务器请求问题居多，  
fetch模块反应出有网络问题和api限制频率问题，目前来看文件夹权限问题只是很小一部分，并不是**百分百**解决

**Comment by chuan01** [comment]
多台vps实测可以解决。

lbion

________________________________
发件人: SomeBottle <notifications@github.com>
发送时间: 星期日, 五月 12, 2019 20:54
收件人: donwa/oneindex
抄送: 一块小海绵; Author
主题: Re: [donwa/oneindex] 百分百解决空白页的方法 (#544)


首先空白页和文件夹权限并没有很大关系，请进行多次测试再得出结论。
空白页主要问题是服务器请求问题居多，
fetch模块反应出有网络问题和api限制频率问题，目前来看文件夹权限问题只是很小一部分，并不是百分百解决

―

**Comment by SomeBottle** [comment]
测试时间有一个月吗

**Comment by chuan01** [comment]
一周

lbion
________________________________

**Comment by chuan01** [comment]
要保证cache和config的权限为777然后才可以正常保存修改内容，比如后台密码和缓存模式或者token，

lbion

________________________________
发件人: 一块小海绵 <me@chuan.ws>
发送时间: 星期日, 五月 12, 2019 20:56
收件人: donwa/oneindex; donwa/oneindex
抄送: Author
主题: Re: [donwa/oneindex] 百分百解决空白页的方法 (#544)

一周

lbion
________________________________

**Comment by SomeBottle** [comment]
vps网络环境也需要不同，这么短时间感觉真的很难作定论，还是继续观察后晚下结论为妙，避免误导。  
毕竟发issue的人太多了，donwa也几个月没管了。

**Comment by SomeBottle** [comment]
php权限方面的问题在安装时就应该是要解决的。

**Comment by chuan01** [comment]
如果使用定时任务更新token要保证config为777才能正常更新

lbion

________________________________
发件人: 一块小海绵 <me@chuan.ws>
发送时间: 星期日, 五月 12, 2019 20:56
收件人: donwa/oneindex; donwa/oneindex
抄送: Author
主题: Re: [donwa/oneindex] 百分百解决空白页的方法 (#544)

一周

lbion
________________________________

**Comment by SomeBottle** [comment]
这个也解决了，但是实测之前仍然有空白页面出现

**Comment by chuan01** [comment]
安装的时候权限检测是通过的，然后还是空白页，修改权限后正常

lbion

________________________________
发件人: 一块小海绵 <me@chuan.ws>
发送时间: 星期日, 五月 12, 2019 21:00
收件人: donwa/oneindex; donwa/oneindex
抄送: Author
主题: Re: [donwa/oneindex] 百分百解决空白页的方法 (#544)

如果使用定时任务更新token要保证config为777才能正常更新

lbion

________________________________
发件人: 一块小海绵 <me@chuan.ws>
发送时间: 星期日, 五月 12, 2019 20:56
收件人: donwa/oneindex; donwa/oneindex
抄送: Author
主题: Re: [donwa/oneindex] 百分百解决空白页的方法 (#544)

一周

lbion
________________________________

**Comment by chuan01** [comment]
建议写在README.md里面，让网友实测效果，望采纳

**Comment by SomeBottle** [comment]
另外微软api也有频率限制，10分钟刷新是不现实的，donwa在回调也没有写刷新失败模块，导致空白页面

**Comment by SomeBottle** [comment]
开发者目前联系不到，建议修改后pull request

**Comment by chuan01** [comment]
好的

**Comment by wo20ljj** [comment]
回头试试。之前换服务器重装都没解决。怀疑账号问题，换账号后正常。。主要我的请求并不高。但是1个半月左右就会出现一次。

**Comment by chuan01** [comment]
好的，记得反馈

**Comment by vircloud** [comment]
用大陆外主机可以解决 99% 问题，囧

**Comment by wo20ljj** [comment]
从来就没用过国内主机，根本不是这个问题！



------------------ 原始邮件 ------------------
发件人: "vircloud.net"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 中午11:51
收件人: "donwa/oneindex"<oneindex@noreply.github.com>; 
抄送: "yanglong"<396866674@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [donwa/oneindex] 百分百解决空白页的方法 (#544)




用大陆外主机可以解决 99% 问题，囧
 
&mdash;

**Comment by hakula139** [comment]
一直是 777，且使用的国外主机，仍然空白页。这个问题主要是 api 调用超限的问题，你的这个方案实际只能解决一部分问题，标题「百分百」很不合适。

**Comment by 91en** [comment]
今天空白了！！！试了，全部777，重启，重建缓存！仍然没有，果然不是权限问题，还是api的问题

**Comment by iiimao** [comment]
绝对API问题。。试了楼主的方式。一样不显示
