### ISSUE TITLE
这是怎么回事?

### ISSUE THREAD

**Issue by huangyingran** [donwa/oneindex#561]
AADSTS650051: Using application 'oneindex' is currently not supported for your organization mails.guet.edu.cn because it is in an unmanaged state. An administrator needs to claim ownership of the company by DNS validation of mails.guet.edu.cn before the application oneindex can be provisioned.

**Comment by libsgh** [comment]
你的账号问题吧，具体的我也不清楚

**Comment by lianeng0** [comment]
遇到同样问题，是不是都不能绑定了

**Comment by SomeBottle** [comment]
账号管理员不提供onedrive服务，如果你能找到管理员，让他开权限。

**Comment by huangyingran** [comment]
明白了
