### ISSUE TITLE
大佬们求教一个问题 那个安装过程中的id和密码应该怎么填？

### ISSUE THREAD

**Issue by Super-Gil** [donwa/oneindex#575]
点了那个链接进Microsoft获取到了client_secret，但是那个client_id是我的邮箱账号吗? 不确定是不是这个问题，后面跳转登陆的时候提示出错
感谢dalao的帮助！

**Comment by Super-Gil** [comment]
在创建应用之后可以登录Microsoft账号了但得到以下错误：
No reply address is registered for the application.
我需要进行怎样的设置才能继续下一步呢？

**Comment by Super-Gil** [comment]
通过必应已解决 感谢

**Comment by Ro0kie** [comment]
你咋解决你倒是说一下啊哥们。。
