### ISSUE TITLE
非“/”目录的配置问题

### ISSUE THREAD

**Issue by Lao-Liu233** [donwa/oneindex#585]
我是小白一个QAQ，用nginx反代后用xxx.com/oneindex来访问，访问文件却会跳转到xxx.com/?/xxx 而不是xxx.com/oneindex/?/xxx，请问该如何配置呢？
不大会搜索这个问题，只能来这儿问了QWQ

**Comment by bafflingbug** [comment]
配置项没有，修改代码吧

**Comment by bafflingbug** [comment]
`oneindex路径/config/base.php`中找到`root_path` 修改为`'root_path' => 'oneindex',`

**Comment by Lao-Liu233** [comment]
> `oneindex路径/config/base.php`中找到`root_path` 修改为`'root_path' => 'oneindex',`

谢谢！之前改了半天愣是没改出来😂
