### ISSUE TITLE
多个网盘都尝试无法播放mp3文件，只想问问有没有相同问题的老哥

### ISSUE THREAD

**Issue by badarch47** [donwa/oneindex#590]
多个网盘都尝试无法播放mp3文件，控制台消息如下：

不支持 HTTP "Content-Type" 设为 "audio/mpeg"。媒体资源 https://dabcoooacnz-my.sharepoint.com/personal/fruitsound_mu…hKazNEY212REdnQlpUbDAwenhKUzdMSmcrSU13b1BpTT0&ApiVersion=2.0 载入失败。 fruitsound.xuehu.biz
无法播放媒体。没有相应格式的解码器：audio/mpeg fruitsound.xuehu.biz
源映射错误：TypeError: Invalid URL: webpack://[name]/webpack/universalModuleDefinition
源 URL：https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
源映射 URL：APlayer.min.js.map

想问下是我自己的问题吗？

**Comment by badarch47** [comment]
看了下貌似是aplayer的问题。。。。。。。。。。。。。。。。。那你们怎么解决的啊

**Comment by tutugreen** [comment]
<audio>?
