### ISSUE TITLE
index.php 显示 Warning: strpos(): Empty needle in [some path]/route.php on line 134

### ISSUE THREAD

**Issue by ZhangTianrong** [donwa/oneindex#599]
是在DD-WRT上安装的，Nginx 1.4.7，PHP 7.3。显示如下：

![image](https://user-images.githubusercontent.com/20651728/68835448-1cfdc980-0686-11ea-96cc-0b4964520a7f.png)

**Comment by SomeBottle** [comment]
能正常安装就不用管，是否影响安装？

**Comment by ZhangTianrong** [comment]
Em……现在看下来是没有问题的。我的问题在于我使用的是一个无管理员的账户，导致无法开放权限给自定义的程序，所以任何第三方软件都无法接入。
