### ISSUE TITLE
希望可以支持cf运行

### ISSUE THREAD

**Issue by RtYkk** [donwa/oneindex#605]
和隔壁goindex相反，我希望oneindex可以支持cf运行，od我有365送了1t

**Comment by SomeBottle** [comment]
https://github.com/heymind/OneDrive-Index-Cloudflare-Worker
onedrive workers版项目

**Comment by RtYkk** [comment]
> https://github.com/heymind/OneDrive-Index-Cloudflare-Worker
> onedrive workers版项目

感谢指路
