### ISSUE TITLE
The requested resource was not found on this server.

### ISSUE THREAD

**Issue by HsunGong** [donwa/oneindex#618]
所有Oneindex的文件只能访问索引，无法点击下载，上传图床后也无法预览。
网址：onedrive.xun-gong.xyz

![image](https://user-images.githubusercontent.com/32933986/73900287-40719280-48ca-11ea-81ce-b45a9c3b25d7.png)

**Comment by Manshaoco** [comment]
我最近发现……我之前一直能用的站点首页现在不显示文件了……都是空白

**Comment by qkqpttgf** [comment]
我看了下，你这服务器没开伪静态，但你oneindex里面勾了伪静态。

**Comment by HsunGong** [comment]
OK，谢谢！
