### ISSUE TITLE
教育邮箱注册的用户好像不能授权。折腾了一晚上。

### ISSUE THREAD

**Issue by Hope-you** [donwa/oneindex#636]
点击绑定账号--登录--直接跳到安装失败，用个人账号可以正常授权使用。这种情况有办法解决吗？

**Comment by SomeBottle** [comment]
感觉微软最近更换了应用api管理平台，可能oneindex没有更新，由此没法授权

**Comment by Hope-you** [comment]
> 感觉微软最近更换了应用api管理平台，可能oneindex没有更新，由此没法授权

不太清楚，但是个人版可以使用呀。是不是只有edu域名管理员才能授权？

**Comment by SomeBottle** [comment]
去年我一直在用oneindex，那个时候edu子账户也是可以的

**Comment by Hope-you** [comment]
> 去年我一直在用oneindex，那个时候edu子账户也是可以的

等大佬更新。

**Comment by sunlewuyou** [comment]
同是教育邮箱，今天发现已经连不上网盘了，也不知道调试，不知道怎么调整，希望作者能及时更新吧！

**Comment by SomeBottle** [comment]
按目前情况来看oneindex算是社区维护了，作者不怎么管了

**Comment by Hope-you** [comment]
> 按目前情况来看oneindex算是社区维护了，作者不怎么管了

配合Aria2自动上传效果怎么实现？有试过吗？之前不知道试了谁的脚本，把usr整个文件夹删了。重装系统了、太难了。

**Comment by ackurdeeve** [comment]
我从昨天下午5点钟开始，之前的rclone挂载的onedrive就不能用了。。
···
2020/03/12 12:29:41 Failed to query available drives: HTTP error 503 (503 Service Unavailable) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"serviceNotAvailable\",\r\n    \"message\": \"Service unavailable\",\r\n    \"innerError\": {\r\n      \"request-id\": \"5fb659ce-538b-4247-940b-0889aceedc18\",\r\n      \"date\": \"2020-03-12T04:29:41\"\r\n    }\r\n  }\r\n}"
···

**Comment by Hope-you** [comment]
> 我从昨天下午5点钟开始，之前的rclone挂载的onedrive就不能用了。。
> ···
> 2020/03/12 12:29:41 Failed to query available drives: HTTP error 503 (503 Service Unavailable) returned body: "{\r\n "error": {\r\n "code": "serviceNotAvailable",\r\n "message": "Service unavailable",\r\n "innerError": {\r\n "request-id": "5fb659ce-538b-4247-940b-0889aceedc18",\r\n "date": "2020-03-12T04:29:41"\r\n }\r\n }\r\n}"
> ···

世道变化太快了。

**Comment by SomeBottle** [comment]
503代表账户超出使用频率已经被限制

**Comment by ackurdeeve** [comment]
使用频率？我大概2分钟往里面写入一个不到1kb的文件，用了10天都没问题。怎么解封？

> 503代表账户超出使用频率已经被限制

**Comment by sunlewuyou** [comment]
默认的重定向地址已经挂了，大家需要修改为自己的域名。

**Comment by SomeBottle** [comment]
> 默认的重定向地址已经挂了，大家需要修改为自己的域名。

是因为访问404吗，如果是这样并不代表挂了.页面默认访问就是404,来着，而且你改成自己的域名的话应用授权返回的code怎么接受？

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/76675925-9936f800-65f9-11ea-8bce-2cb6b6e8e489.png)

**Comment by SomeBottle** [comment]
你这个太古老了吧，早就换成https://oneindex.github.io/ 了

**Comment by sunlewuyou** [comment]
https://oneindex.github.io/  这个也挂了，就是这几天挂了才导致大家授权失效的，善意提醒一下大家。对症下药。

**Comment by sunlewuyou** [comment]
https://oneindex.github.io/ 这个是我默认转发的地址，安装成功后使用了几天突然就不能用了，只好自己做转发重新安装了，自己的域名最稳妥了，希望大家也跟我一样安装的时候多做这一步吧。

**Comment by Hope-you** [comment]
> https://oneindex.github.io/ 这个是我默认转发的地址，安装成功后使用了几天突然就不能用了，只好自己做转发重新安装了，自己的域名最稳妥了，希望大家也跟我一样安装的时候多做这一步吧。

我用的作者默认的转发，edu教育版是**不能**授权，但是个人**完美使用**，这不是_稳不稳定_的问题，是_可不可以_的问题，哈哈。

**Comment by iamwwc** [comment]
@Hope-you 自己买的business商业协作版的话能绑定oneindex吗？

**Comment by Hope-you** [comment]
> @Hope-you 自己买的business商业协作版的话能绑定oneindex吗？

好像可以吧，试一下呗，不过网速堪忧，我凌晨3点的时候使用网速可以达到200m宽带的满速，其他时间只有70k/s左右。(移动宽带和电信宽带)

**Comment by waloyn** [comment]
> > @Hope-you 自己买的business商业协作版的话能绑定oneindex吗？
> 
> 好像可以吧，试一下呗，不过网速堪忧，我凌晨3点的时候使用网速可以达到200m宽带的满速，其他时间只有70k/s左右。(移动宽带和电信宽带)

这个速度取决于全局管理员申请的时候填的地区吧，如果是中国，onedrive是由世纪互联运营的，速度相对来说要快很多。

**Comment by llccd** [comment]
我好像解决了这个问题，用edu教育版账号登陆https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade ，打开"拥有的应用程序"-"oneindex"-"查看api权限"，添加`Files.ReadWrite.All`和`offline_access`权限

**Comment by Hope-you** [comment]
> 我好像解决了这个问题，用edu教育版账号登陆https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade ，打开"拥有的应用程序"-"oneindex"-"查看api权限"，添加`Files.ReadWrite.All`和`offline_access`权限
登不上，我用的是我们学校的edu邮箱。
![image](https://user-images.githubusercontent.com/34697553/76961243-fca58a80-6957-11ea-852e-9cb78ed47c4d.png)

**Comment by iamwwc** [comment]
大家的教育邮箱毕业之后还能用吗？我担心毕业之后用不了数据就都没了

**Comment by llccd** [comment]
>> 我好像解决了这个问题，用edu教育版账号登陆<https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade>，打开"拥有的应用程序"-"oneindex"-"查看api权限"，添加`Files.ReadWrite.All`和`offline_access`权限
>
> 登不上，我用的是我们学校的edu邮箱。
> ![image](https://user-images.githubusercontent.com/34697553/76961243-fca58a80-6957-11ea-852e-9cb78ed47c4d.png)

看起来你的账号好像注册的是中国特色的世纪互联版本，程序里默认的api地址都是国际版的，打开index.php，去掉第5行“世纪互联”下的注释试试

**Comment by Hope-you** [comment]
> > > 我好像解决了这个问题，用edu教育版账号登陆https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade，打开"拥有的应用程序"-"oneindex"-"查看api权限"，添加`Files.ReadWrite.All`和`offline_access`权限
> > 
> > 
> > 登不上，我用的是我们学校的edu邮箱。
> > ![image](https://user-images.githubusercontent.com/34697553/76961243-fca58a80-6957-11ea-852e-9cb78ed47c4d.png)
> 
> 看起来你的账号好像注册的是中国特色的世纪互联版本，程序里默认的api地址都是国际版的，打开index.php，去掉第5行“世纪互联”下的注释试试

还是没有用。哈哈哈哈。

**Comment by llccd** [comment]
添加api权限这步也要做，把`portal.azure.com`换成`portal.azure.cn`试试能不能登进去添加api权限

**Comment by Hope-you** [comment]
> 添加api权限这步也要做，把`portal.azure.com`换成`portal.azure.cn`试试能不能登进去添加api权限

直接注销，等不了。可能是黑号吧。只能用官方的软件。

**Comment by Hope-you** [comment]
> 大家的教育邮箱毕业之后还能用吗？我担心毕业之后用不了数据就都没了

应该取决于学校回收不回收邮箱。

**Comment by Hope-you** [comment]
自定义域名出了问题。没有管理员的账号不可以授权第三方应用。
