### ISSUE TITLE
edu教育邮箱，点击绑定账号时出现，系统内没有***邮箱域名***请务必键入正确的域。

### ISSUE THREAD

**Issue by Hope-you** [donwa/oneindex#639]

**Comment by Hope-you** [comment]
自定义域名的问题

**Comment by Rom2333** [comment]
我遇到过 没管理员就只有1T




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hope-you"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 凌晨2:34
收件人:&nbsp;"donwa/oneindex"<oneindex@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[donwa/oneindex] edu教育邮箱，点击绑定账号时出现，系统内没有***邮箱域名***请务必键入正确的域。 (#639)





 

 问题如图所示，有朋友遇到过吗？学校邮箱是没有管理员的，容量1个t。
