### ISSUE TITLE
GearHost php5.6搭建，经常性列表为空

### ISSUE THREAD

**Issue by Kevin0521-AI2** [donwa/oneindex#644]
使用GearHost php5.6搭建，经常性无法拉取onedrive列表。
管理页面“页面缓存”-“清除所有缓存”，之后就可以正常拉取列表。
请问该问题如何解决呢？能否设置定时、自动清除缓存？或者其他方法可正常拉取列表？
感谢！

**Comment by SomeBottle** [comment]
oneindex一直有这个问题，原因是api限制.如果文件很多，每次重建缓存对api的请求量是很大的。这个问题只能用别人修改过的oneindex解决。donwa目前已经很少维护了，在这里发issue几乎是没效果的，建议还是换第三方的或者彻底改用其他程序。

**Comment by Kevin0521-AI2** [comment]
> oneindex一直有这个问题，原因是api限制.如果文件很多，每次重建缓存对api的请求量是很大的。这个问题只能用别人修改过的oneindex解决。donwa目前已经很少维护了，在这里发issue几乎是没效果的，建议还是换第三方的或者彻底改用其他程序。

嗯嗯，小白了解了。感谢您的回复。
另，是否方便推荐一款可规避该问题的第三方oneindex呢？或者其他OneDrive挂载程序？

**Comment by SomeBottle** [comment]
> > oneindex一直有这个问题，原因是api限制.如果文件很多，每次重建缓存对api的请求量是很大的。这个问题只能用别人修改过的oneindex解决。donwa目前已经很少维护了，在这里发issue几乎是没效果的，建议还是换第三方的或者彻底改用其他程序。
> 
> 嗯嗯，小白了解了。感谢您的回复。
> 另，是否方便推荐一款可规避该问题的第三方oneindex呢？或者其他OneDrive挂载程序？

不好说，你看你现在在哪里，是github。直接全站搜索onedrive，搜索语言类型选php就能出来很多。我自己用的是自己写的一个，但是功能不多

**Comment by Kevin0521-AI2** [comment]
好的，了解，感谢指导！
Have a nice day!
