### ISSUE TITLE
目录名含空格cli刷新缓存会卡住

### ISSUE THREAD

**Issue by heroxin** [donwa/oneindex#83]
若有目录的目录名含空格，php cli 刷新缓存时会卡在该目录无法继续，将目录名中的空格改成下划线则恢复正常。仅目录名含空格时会出现此问题，文件名含空格则不影响

**Comment by donwa** [comment]
收到，我调试下。

**Comment by cbgilbert** [comment]
同样的问题，目录名空格改下划线即解决。文件名未测试。

**Comment by heroxin** [comment]
3.0版此问题已解决
